// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      var deck;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      this.get('playerHand').on('stood', (function(_this) {
        return function() {
          return _this.get('dealerHand').hit();
        };
      })(this));
      this.get('playerHand').on('playerLoses', (function(_this) {
        return function() {
          return _this.trigger('playerLoses', _this);
        };
      })(this));
      this.get('dealerHand').on('playerWins', (function(_this) {
        return function() {
          return _this.trigger('playerWins', _this);
        };
      })(this));
      return this.get('dealerHand').on('checkGameOutcome', (function(_this) {
        return function() {
          return _this.checkResults();
        };
      })(this));
    };

    App.prototype.checkResults = function() {
      var dealerMaxScore, dealerScores, playerMaxScore, playerScores, score, _i, _j, _len, _len1;
      playerScores = this.get('playerHand').scores();
      dealerScores = this.get('dealerHand').scores();
      playerMaxScore = 0;
      for (_i = 0, _len = playerScores.length; _i < _len; _i++) {
        score = playerScores[_i];
        if (score <= 21) {
          playerMaxScore = Math.max(playerMaxScore, score);
        }
      }
      dealerMaxScore = 0;
      for (_j = 0, _len1 = dealerScores.length; _j < _len1; _j++) {
        score = dealerScores[_j];
        if (score <= 21) {
          dealerMaxScore = Math.max(dealerMaxScore, score);
        }
      }
      if (playerMaxScore > dealerMaxScore) {
        return this.trigger('playerWins', this);
      } else if (playerMaxScore < dealerMaxScore) {
        return this.trigger('playerLoses', this);
      } else if (playerMaxScore === dealerMaxScore) {
        return this.trigger('playerTies', this);
      }
    };

    return App;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=App.map
