// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.hit = function() {
      this.add(this.deck.pop()).last();
      if (this.isDealer != null) {
        return this.checkDealer();
      } else {
        return this.checkBust();
      }
    };

    Hand.prototype.stand = function() {
      return this.trigger('stood', this);
    };

    Hand.prototype.scores = function() {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      if (hasAce) {
        return [score, score + 10];
      } else {
        return [score];
      }
    };

    Hand.prototype.checkBust = function() {
      if (this.scores()[0] > 21) {
        return this.trigger('playerLoses', this);
      }
    };

    Hand.prototype.checkDealer = function() {
      var dealerScore, length, score, _i, _len, _results;
      dealerScore = this.scores().reverse();
      length = dealerScore.length;
      _results = [];
      for (_i = 0, _len = dealerScore.length; _i < _len; _i++) {
        score = dealerScore[_i];
        if (score < 17) {
          this.hit();
        }
        if ((17 <= score && score <= 21)) {
          this.trigger('checkGameOutcome', this);
        }
        if (score > 21) {
          _results.push(this.trigger('playerWins', this));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Hand.map
